#!/usr/bin/perl
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2006, 2007, 2009, 2010, 2013, 2014, 2016 Synacor, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software Foundation,
# version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
# ***** END LICENSE BLOCK *****
# 

sub handleTerm {
	print "SIGTERM received, exiting\n";
	qx(/opt/zimbra/bin/zmcontrol stop >> /opt/zimbra/log/zcs.log 2>&1);
	exit 0;
}

$SIG{TERM} = \&handleTerm;

if ($ARGV[0] eq "start") {
	qx(/opt/zimbra/bin/zmcontrol start >> /opt/zimbra/log/zcs.log 2>&1);
	sleep;
}
