#!/bin/bash
#
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2015 Zimbra, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software Foundation,
# version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
# ***** END LICENSE BLOCK *****
#
#
#
# Consul CHECK script for Zimbra MailStoreServer & MailStoreSSLServer.
# See https://www.consul.io/docs/agent/checks.html
#
# Return:
#   0 if check is passing
#   1 if check is warning
#   (other) if check is failing
#

URL="$1"
RES=`curl -sw '%{http_code}' -I -k -o /dev/null ${URL}`

if [[ $RES -eq 200 ]]; then
	echo "${URL}... OK"
	exit 0
else
	echo "${URL}... FAILED"
	exit 2
fi
