#!/usr/bin/python
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2015 Zimbra, Inc.
# 
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software Foundation,
# version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
# ***** END LICENSE BLOCK *****
#
#
#
# Consul CHECK script for Zimbra MailStoreServer & MailStoreSSLServer. See https://www.consul.io/docs/agent/checks.html
#
# Return:
#   0 if check is passing
#   1 if check is warning
#   (other) if check is failing
#

import argparse
import urllib2

arg_parser = argparse.ArgumentParser()
arg_parser.add_argument('-url', help='URL', default='https://127.0.0.1')
arg_parser.add_argument('-timeout', help='Timeout in seconds', type=int, default=10)
args = arg_parser.parse_args()


data = """<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
<soap:Body><PingRequest xmlns="urn:zimbraAccount"/></soap:Body>
</soap:Envelope>"""

try:
	req = urllib2.Request(args.url + '/service/soap')
	req.add_header('Content-Type', 'text/xml')
	res = urllib2.urlopen(req, data, args.timeout);
	print "{0}... OK".format(args.url)

except (urllib2.HTTPError, urllib2.URLError) as err:
	print "{0}... FAILED: {1}".format(args.url, err)
	exit(2)
except socket.timeout, err:
	print "{0}... FAILED: {1}".format(args.url, err)
	exit(2)
