#!/bin/bash
#
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2008, 2009, 2010, 2012, 2013 Zimbra Software, LLC.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.4 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
#; ***** END LICENSE BLOCK *****
# 

if [ x`whoami` != xzimbra ]; then
    echo Error: must be run as zimbra user
    exit 1
fi

zimbra_java_home=/opt/zimbra/java
jspc_src_dir=/opt/zimbra/mailboxd/webapps/zimbra
jspc_build_dir=/opt/zimbra/mailboxd/work/zimbra/jsp
jspc_class_path="/opt/zimbra/jetty/lib:/opt/zimbra/jetty/lib/jsp:/opt/zimbra/jetty/lib/ext:/opt/zimbra/jetty/lib/plus:/opt/zimbra/jetty/lib/naming:/opt/zimbra/lib/ext:/opt/zimbra/jetty/common/lib:/opt/zimbra/jetty/webapps/zimbra/WEB-INF/lib"

extensions="backup clamscanner network zimbra-license zimbrahsm zimbrasync"
ext_dir="/opt/zimbra/lib/ext-common"
for i in $extensions; do
  if [ -d "/opt/zimbra/lib/ext/$i" ]; then
   jspc_class_path="${jspc_class_path}:${ext_dir}/$i"
  fi
done

for i in `ls /opt/zimbra/jetty/lib/jsp/*.jar`; do
  if [ x"$class_path" = "x" ]; then
    class_path="$i"
  else 
    class_path="${class_path}:$i"
  fi
done

java_version=$(${zimbra_java_home}/bin/java -version 2>&1 | grep "java version" | sed -e 's/"//g' | awk '{print $NF}' | awk -F_ '{print $1}')
if [ x"$java_version" = "x1.6.0" ]; then
  java_options="-XX:ErrorFile=/opt/zimbra/log"
else
  java_options=""
fi

java_cmd="${zimbra_java_home}/bin/java $java_options \
  -client -Xmx256m \
  -Dzimbra.home=/opt/zimbra \
  -Djava.library.path=/opt/zimbra/lib \
  -Djava.ext.dirs=${jspc_class_path}"

if [ -d "${jspc_build_dir}" ]; then
  rm -rf ${jspc_build_dir}
fi
mkdir ${jspc_build_dir}

compile_jsp() {
  file=shift
  ${java_cmd} org.apache.jasper.JspC -v -d ${jspc_build_dir} -webapp ${jspc_src_dir} -uriroot ${jspc_src_dir} -compile -classpath ${class_path}
  return $?
}

compile_jsp ${param_jspfile}
if [ $? = 0 ]; then
  echo "done."
else
  echo "failed."
fi
