#!/usr/bin/perl -w
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2007, 2009, 2010, 2012, 2013 Zimbra, Inc.
# 
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software Foundation,
# version 2 of the License.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
# ***** END LICENSE BLOCK *****
# 

use strict;
use Getopt::Long;

my @interfaces = ();
open INTS, "/sbin/ifconfig | grep ' addr' |";
foreach (<INTS>) {
  chomp;
  if ($_ =~ /inet6/) {
    s/.*inet6 //;
    s/addr: //;
	s/ Scope:.*//;
	s/\// Mask:/;
  } else {
    s/.*inet //;
    s/addr://;
    s/.(bcast|broadcast)[0-9:.\s]*//ig;
    s/.netmask\s/  Mask:/;
  }
#  s/\s.*//;
#  s/[a-zA-Z:]//g;
  next if /^$/;
  push @interfaces, "addr:".$_;
}
close INTS;
my %seen;
if (scalar @interfaces) {
  foreach (@interfaces) {
    $seen{$_}++;
    print "$_\n" unless ($seen{$_} > 1);
  }
}

#/sbin/ifconfig | grep '	inet ' | sed -e 's/.*inet //' -e 's/\s.*//' -e 's/[a-zA-Z:]//g' | uniq 
#/sbin/ifconfig | sed -e '/^[ 	] *inet /!d' -e 's/.*inet //' -e 's/\s.*//' -e 's/[a-zA-Z:]//g' | uniq 
