#!/usr/bin/perl -w
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2007, 2009, 2010, 2012, 2013 Zimbra Software, LLC.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.4 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

use strict;
use Getopt::Long;
use NetAddr::IP;

my @interfaces = ();
open INTS, "/sbin/ip addr | grep inet |";
foreach (<INTS>) {
  chomp;
  my $mask;
  my $ip;
  if ($_ =~ /scope link/) {
    next;
  }
  if ($_ =~ /inet6/) {
    s/.*inet6 //;
    s/ brd.*//;
	s/ scope.*//;
	($ip, $mask) = split /\//, $_, 2;
	s/\/.*//;
  } else {
    s/.*inet //;
    s/ brd.*//;
	s/ scope.*//;
    $ip = new NetAddr::IP "$_";
    $mask = $ip->mask();
	s/\/.*//;
  }
  next if /^$/;
  push @interfaces, "addr:".$_." Mask:".$mask;
}
close INTS;
my %seen;
if (scalar @interfaces) {
  foreach (@interfaces) {
    $seen{$_}++;
    print "$_\n" unless ($seen{$_} > 1);
  }
}
