#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007, 2009, 2010, 2012, 2013 Zimbra Software, LLC.
# 
# The contents of this file are subject to the Zimbra Public License
# Version 1.4 ("License"); you may not use this file except in
# compliance with the License.  You may obtain a copy of the License at
# http://www.zimbra.com/license.
# 
# Software distributed under the License is distributed on an "AS IS"
# basis, WITHOUT WARRANTY OF ANY KIND, either express or implied.
# ***** END LICENSE BLOCK *****
# 

# snmp_notify 1|0
# snmp_trap_host <hostname|ip>
# smtp_notify 1|0
# smtp_source <email address>
# smtp_destination <email address>

source "/opt/zimbra/bin/zmshutil" || exit 1
zmsetvars

if [ ${snmp_notify} = "1" ]; then
	SOURCEFILE=/opt/zimbra/snmp/share/snmp/snmpd.conf.in
	FILE=/opt/zimbra/conf/snmpd.conf
	echo creating $FILE
	cat ${SOURCEFILE} | sed -e "s/@@SNMPHOST@@/${snmp_trap_host}/g" > ${FILE}
fi

SWFILE=/opt/zimbra/conf/swatchrc

echo creating $SWFILE
cat ${SWFILE}.in | \
	sed -e "s/@@DOSNMPNOTIFICATIONS@@/${snmp_notify}/g" \
	-e "s/@@DOSMTPNOTIFICATIONS@@/${smtp_notify}/g" \
	-e "s/@@ADMINEMAIL@@/${smtp_source}/g" \
	-e "s/@@PHCEMAIL@@/${smtp_destination}/g" \
	-e "s/@@HOSTNAME@@/${zimbra_server_hostname}/g" \
	> ${SWFILE}
