#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2005, 2006, 2007, 2009, 2010, 2013, 2014 Zimbra, Inc.
# 
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software Foundation,
# version 2 of the License.
# 
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <http://www.gnu.org/licenses/>.
# ***** END LICENSE BLOCK *****
# 

# snmp_notify 1|0
# snmp_trap_host <hostname|ip>
# smtp_notify 1|0
# smtp_source <email address>
# smtp_destination <email address>

source "/opt/zimbra/bin/zmshutil" || exit 1
zmsetvars \
	zimbra_server_hostname \
	snmp_notify \
	smtp_notify 

if [ ${snmp_notify} = "1" ]; then
	zmsetvars \
		snmp_trap_host 
	SOURCEFILE=/opt/zimbra/snmp/share/snmp/snmpd.conf.in
	FILE=/opt/zimbra/conf/snmpd.conf
	echo creating $FILE
	cat ${SOURCEFILE} | sed -e "s/@@SNMPHOST@@/${snmp_trap_host}/g" > ${FILE}
fi

# Many backslashes to make sure '@' gets quoted in final perl

if [ ${smtp_notify} = "1" ]; then
	zmsetvars \
		smtp_source \
		smtp_destination

	smtp_source=`echo ${smtp_source} | sed -e 's/@/\\\\\\\@/'`

	smtp_destination=`echo ${smtp_destination} | sed -e 's/@/\\\\\\\@/'`
fi

SWFILE=/opt/zimbra/conf/swatchrc

echo creating $SWFILE
cat ${SWFILE}.in | \
	sed -e "s/@@DOSNMPNOTIFICATIONS@@/${snmp_notify}/g" \
	-e "s/@@DOSMTPNOTIFICATIONS@@/${smtp_notify}/g" \
	-e "s/@@ADMINEMAIL@@/${smtp_source}/g" \
	-e "s/@@PHCEMAIL@@/${smtp_destination}/g" \
	-e "s/@@HOSTNAME@@/${zimbra_server_hostname}/g" \
	> ${SWFILE}
