#!/bin/bash
# 
# ***** BEGIN LICENSE BLOCK *****
# Zimbra Collaboration Suite Server
# Copyright (C) 2010, 2011, 2012, 2013, 2014, 2016 Synacor, Inc.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software Foundation,
# version 2 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
# without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU General Public License for more details.
# You should have received a copy of the GNU General Public License along with this program.
# If not, see <https://www.gnu.org/licenses/>.
# ***** END LICENSE BLOCK *****
# 


usage() {
  echo "Usage: $0"
  exit 1
}

if [ "$(whoami)" != "zimbra" ]; then
  echo Error: must be run as zimbra user
  exit 1
fi

source /opt/zimbra/bin/zmshutil || exit 1
zmsetvars

# shellcheck disable=SC2154
download_dir=${mailboxd_directory}/webapps/zimbra/downloads
index=${download_dir}/index.html

admin_dir=${mailboxd_directory}/webapps/zimbraAdmin/WEB-INF/classes/messages
zmsg=${admin_dir}/ZaMsg.properties

function find_download_filename {
    fname="$1"
    find "${download_dir}" -name "$fname" -exec basename '{}' \;
}

if [ -d "${download_dir}" ]; then
  ZCO_32BIT=$(find_download_filename "ZimbraConnectorOLK*x86.msi")
  ZCO_64BIT=$(find_download_filename "ZimbraConnectorOLK*x64.msi")
  PST_IMPORT=$(find_download_filename "ZCSPSTImportWizard*")
  EXCHANGE_MIG_WIZARD=$(find_download_filename "ZCSExchangeMigrationWizard*")
  DOMINO_MIG_WIZARD=$(find_download_filename "ZCSDominoMigrationWizard*")
  GENERAL_MIG_WIZARD_32BIT=$(find_download_filename "ZimbraMigration_*_x86.zip")
  GENERAL_MIG_WIZARD_64BIT=$(find_download_filename "ZimbraMigration_*_x64.zip")

  sed -e "s/@@ZCO_32BIT@@/${ZCO_32BIT}/" \
  -e "s/@@ZCO_64BIT@@/${ZCO_64BIT}/" \
  -e "s/@@PST_IMPORT@@/${PST_IMPORT}/" \
  -e "s/@@EXCHANGE_MIG_WIZARD@@/${EXCHANGE_MIG_WIZARD}/" \
  -e "s/@@GENERAL_MIG_WIZARD_32BIT@@/${GENERAL_MIG_WIZARD_32BIT}/" \
  -e "s/@@GENERAL_MIG_WIZARD_64BIT@@/${GENERAL_MIG_WIZARD_64BIT}/" \
  -e "s/@@DOMINO_MIG_WIZARD@@/${DOMINO_MIG_WIZARD}/" > "${index}" < "${index}.in"

  if [ -f "${zmsg}" ]; then
    sed -i -e "s#ZimbraConnectorOLK_.*x86.msi#${ZCO_32BIT}#" \
      -e "s#ZimbraConnectorOLK_.*x64.msi#${ZCO_64BIT}#" "${zmsg}"
  fi
fi

exit 0

